/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AnonymousBallotInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "advanceElectionState"
      | "candidateIds"
      | "electionState"
      | "getCandidateIds"
      | "getElectionState"
      | "getTotalVotes"
      | "getVoteCount"
      | "hasVoted"
      | "hasVoterVoted"
      | "isValidCandidate"
      | "markVoters"
      | "recordVotes"
      | "relayer"
      | "totalVotes"
      | "voteCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ElectionStateChanged"
      | "VotersMarked"
      | "VotesRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "advanceElectionState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "candidateIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electionState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidateIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getElectionState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hasVoted", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasVoterVoted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidCandidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markVoters",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVotes",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteCount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "advanceElectionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectionState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasVoterVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markVoters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteCount", data: BytesLike): Result;
}

export namespace ElectionStateChangedEvent {
  export type InputTuple = [newState: BigNumberish];
  export type OutputTuple = [newState: bigint];
  export interface OutputObject {
    newState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotersMarkedEvent {
  export type InputTuple = [count: BigNumberish];
  export type OutputTuple = [count: bigint];
  export interface OutputObject {
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotesRecordedEvent {
  export type InputTuple = [count: BigNumberish];
  export type OutputTuple = [count: bigint];
  export interface OutputObject {
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousBallot extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousBallot;
  waitForDeployment(): Promise<this>;

  interface: AnonymousBallotInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  advanceElectionState: TypedContractMethod<[], [void], "nonpayable">;

  candidateIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  electionState: TypedContractMethod<[], [bigint], "view">;

  getCandidateIds: TypedContractMethod<[], [bigint[]], "view">;

  getElectionState: TypedContractMethod<[], [bigint], "view">;

  getTotalVotes: TypedContractMethod<[], [bigint], "view">;

  getVoteCount: TypedContractMethod<
    [candidateId: BigNumberish],
    [bigint],
    "view"
  >;

  hasVoted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  hasVoterVoted: TypedContractMethod<[voterHash: BytesLike], [boolean], "view">;

  isValidCandidate: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  markVoters: TypedContractMethod<
    [voterHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  recordVotes: TypedContractMethod<
    [_candidateIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  totalVotes: TypedContractMethod<[], [bigint], "view">;

  voteCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "advanceElectionState"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "candidateIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "electionState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCandidateIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getElectionState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteCount"
  ): TypedContractMethod<[candidateId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasVoterVoted"
  ): TypedContractMethod<[voterHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidCandidate"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "markVoters"
  ): TypedContractMethod<[voterHashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordVotes"
  ): TypedContractMethod<[_candidateIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "ElectionStateChanged"
  ): TypedContractEvent<
    ElectionStateChangedEvent.InputTuple,
    ElectionStateChangedEvent.OutputTuple,
    ElectionStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "VotersMarked"
  ): TypedContractEvent<
    VotersMarkedEvent.InputTuple,
    VotersMarkedEvent.OutputTuple,
    VotersMarkedEvent.OutputObject
  >;
  getEvent(
    key: "VotesRecorded"
  ): TypedContractEvent<
    VotesRecordedEvent.InputTuple,
    VotesRecordedEvent.OutputTuple,
    VotesRecordedEvent.OutputObject
  >;

  filters: {
    "ElectionStateChanged(uint8)": TypedContractEvent<
      ElectionStateChangedEvent.InputTuple,
      ElectionStateChangedEvent.OutputTuple,
      ElectionStateChangedEvent.OutputObject
    >;
    ElectionStateChanged: TypedContractEvent<
      ElectionStateChangedEvent.InputTuple,
      ElectionStateChangedEvent.OutputTuple,
      ElectionStateChangedEvent.OutputObject
    >;

    "VotersMarked(uint256)": TypedContractEvent<
      VotersMarkedEvent.InputTuple,
      VotersMarkedEvent.OutputTuple,
      VotersMarkedEvent.OutputObject
    >;
    VotersMarked: TypedContractEvent<
      VotersMarkedEvent.InputTuple,
      VotersMarkedEvent.OutputTuple,
      VotersMarkedEvent.OutputObject
    >;

    "VotesRecorded(uint256)": TypedContractEvent<
      VotesRecordedEvent.InputTuple,
      VotesRecordedEvent.OutputTuple,
      VotesRecordedEvent.OutputObject
    >;
    VotesRecorded: TypedContractEvent<
      VotesRecordedEvent.InputTuple,
      VotesRecordedEvent.OutputTuple,
      VotesRecordedEvent.OutputObject
    >;
  };
}
